# Generated by Django 3.0.7 on 2020-12-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genre', models.IntegerField(choices=[(1, 'rock'), (2, 'Heavy Metal'), (3, 'Thrash Metal'), (4, 'Others')])),
                ('dof', models.DateField()),
            ],
        ),
    ]
