# Generated by Django 3.0.7 on 2020-12-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(choices=[(1, 'Best'), (2, 'Good'), (3, 'Worst')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Band')),
            ],
        ),
    ]
